<?php

/*
 * Implementation of hook_menu
 */
function houston_connect_menu() {
  $items['admin/settings/houston_connect'] = array(
    'title' => t('Houston Connect'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('houston_connect_settings'),
    'access arguments' => array('adminster houston connect'),
    'type' => MENU_LOCAL_TASK
  );
  
  return $items;
}

/*
 * Implementation of hook_perm
 */
function houston_connect_perm() {
  return array('adminster houston connect');
}

/*
 * Houston connect settings form
 */
function houston_connect_settings() {
  $form['houston_connect_api_key'] = array(
    '#title' => t('API Key'),
    '#type' => 'textfield',
    '#default_value' => variable_get('houston_connect_api_key', ''),
  );
  
  return system_settings_form($form);
}